### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jessepisel** [jessepisel/summer_fellows#195]
@dingdonged Reading in a random .LAS file results in an error from `lasio`. Here is code to reproduce the error
<pre><code>from aliaser.keyword_tree import Alias
a = Alias()
a.parse(PATH_TO_LAS_FILE+"/533095C.las"
</pre></code>

which returns the following error:
<pre><code>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jrp4932\AppData\Local\Continuum\anaconda3\envs\aliaser\lib\site-packages\aliaser-0.0-py3.7.egg\aliaser\keyword_tree.py", line 220, in parse
    df = self.make_df(path)
  File "C:\Users\jrp4932\AppData\Local\Continuum\anaconda3\envs\aliaser\lib\site-packages\aliaser-0.0-py3.7.egg\aliaser\keyword_tree.py", line 306, in make_df
    description.append(str(las.curves[i].descr).lower())
  File "C:\Users\jrp4932\AppData\Local\Continuum\anaconda3\envs\aliaser\lib\site-packages\lasio\las_items.py", line 292, in __getitem__
    raise KeyError('%s not in %s' % (key, self.keys()))
KeyError: "qn not in ['DEPT', 'GR', 'TEMP', 'DTMP']"</pre></code>

It looks like this is originating in `lasio` when `make_df` calls the curve names. Opening the .LAS file with `lasio` everything appears to behave normally. This means it must be an issue in the `make_df` method. 

I will look into this a bit, can you help by seeing if you can trace down the bug?

**Comment by jessepisel** [comment]
It gets even weirder. If I run this in a notebook it is fine. If I run this in a console that is when the error shows up

**Comment by jessepisel** [comment]
I haven't been able to reproduce this error since installing the package locally. I am going to close this issue. I think it was related to importing the package and modules without the install.
